### ISSUE TITLE
Docker Hub image is broken

### ISSUE THREAD

**Issue by slavanap** [Project-OSRM/osrm-frontend#297]
`docker run -p 9966:9966 osrm/osrm-frontend`

fails with the following message:

```
PS C:\Users\Vyacheslav> docker run -p 9966:9966 osrm/osrm-frontend

> osrm-frontend@0.4.0 start /src
> npm run build && npm run start-index


> osrm-frontend@0.4.0 build /src
> npm run replace && npm run compile && cp node_modules/leaflet/dist/leaflet.css css/leaflet.css


> osrm-frontend@0.4.0 replace /src
> node ./scripts/replace.js


> osrm-frontend@0.4.0 compile /src
> browserify -d src/index.js -s osrm > bundle.raw.js && uglifyjs bundle.raw.js -c -m --source-map=bundle.js.map -o bundle.js

Error: Cannot find module '../i18n/pt-BR' from '/src/src'
    at /src/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/src/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/src/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /src/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)

npm ERR! Linux 4.9.125-linuxkit
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "compile"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! osrm-frontend@0.4.0 compile: `browserify -d src/index.js -s osrm > bundle.raw.js && uglifyjs bundle.raw.js -c -m --source-map=bundle.js.map -o bundle.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the osrm-frontend@0.4.0 compile script 'browserify -d src/index.js -s osrm > bundle.raw.js && uglifyjs bundle.raw.js -c -m --source-map=bundle.js.map -o bundle.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the osrm-frontend package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browserify -d src/index.js -s osrm > bundle.raw.js && uglifyjs bundle.raw.js -c -m --source-map=bundle.js.map -o bundle.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs osrm-frontend
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls osrm-frontend
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /src/npm-debug.log

npm ERR! Linux 4.9.125-linuxkit
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! osrm-frontend@0.4.0 build: `npm run replace && npm run compile && cp node_modules/leaflet/dist/leaflet.css css/leaflet.css`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the osrm-frontend@0.4.0 build script 'npm run replace && npm run compile && cp node_modules/leaflet/dist/leaflet.css css/leaflet.css'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the osrm-frontend package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run replace && npm run compile && cp node_modules/leaflet/dist/leaflet.css css/leaflet.css
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs osrm-frontend
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls osrm-frontend
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /src/npm-debug.log

npm ERR! Linux 4.9.125-linuxkit
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! osrm-frontend@0.4.0 start: `npm run build && npm run start-index`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the osrm-frontend@0.4.0 start script 'npm run build && npm run start-index'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the osrm-frontend package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && npm run start-index
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs osrm-frontend
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls osrm-frontend
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /src/npm-debug.log
```

**Comment by freenerd** [comment]
I think this should have been fixed with https://github.com/Project-OSRM/osrm-frontend/pull/298. Can you try again in an hour when the new docker image has been built?

**Comment by slavanap** [comment]
Thanks! It's working now.
