### ISSUE TITLE
npm install fails on Windows

### ISSUE THREAD

**Issue by pig2018** [Project-OSRM/osrm-frontend#300]
I press "npm install" ,the result error is  
```
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.22.0-customsnapping.2/Release/node-v64-win32-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (D:\003——探索\osrm-backend\node_modules\node-pre-gyp\lib\install.js:149:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:187:15)
node-pre-gyp ERR! stack     at Request.onRequestResponse (D:\003——探索\osrm-backend\node_modules\request\request.js:1066:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:182:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:555:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:441:20)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:182:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:283:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:264:11)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\003——探索\\osrm-backend\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd D:\003——探索\osrm-backend
node-pre-gyp ERR! node -v v10.14.1
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.22.0-customsnapping.2/Release/node-v64-win32-x64.tar.gz
'.' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! osrm@5.22.0-customsnapping.2 install: `node-pre-gyp install --fallback-to-build=false || ./scripts/node_install.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the osrm@5.22.0-customsnapping.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\nodejs\node_cache\_logs\2019-03-24T12_57_55_404Z-debug.log

D:\003——探索\osrm-backend>npm run compile
npm ERR! missing script: compile

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\nodejs\node_cache\_logs\2019-03-24T13_03_54_420Z-debug.log

D:\003——探索\osrm-backend>npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\nodejs\node_cache\_logs\2019-03-24T13_08_02_685Z-debug.log
```

**Comment by danpat** [comment]
Are you trying to do `npm install` inside the OSRM project, or add it as a dependency to another?

If the first, try doing `npm install --ignore-scripts` - this will prevent `node-pre-gyp` from being triggered as a post-install script - it isn't needed to simply install dependencies.

If you want the second, then unfortunately, we don't publish the pre-built binary part needed for node bindings on Windows to work.

**Comment by pig2018** [comment]
I want to choose the first;
```
D:\003——探索\osrm-backend>npm install --ignore-scripts
[         .........] - extract:uid-number: sill extract uid-number@0.0.6 extracted to D:\003——探索\osrm-backend\node_m[           .......] - extract:tar: sill extract tar@2.2.1 extracted to D:\003——探索\osrm-backend\node_modules\.stagin[           .......] - extract:tar: sill extract tar@2.2.1 extracted to D:\003——探索\osrm-backend\node_modules\.stagin[           .......] - extract:tar: sill extract tar@2.2.1 extracted to D:\003——探索\osrm-backend\node_modules\.stagin[           .......] - extract:tar: sill extract tar@2.2.1 extracted to D:\003——探索\osrm-backend\node_modules\.stagin[           .......] - extract:tar: sill extract tar@2.2.1 extracted to D:\003——探索\osrm-backend\node_modules\.stagin[           .......] | extract:tar: sill extract tar@2.2.1 extracted to D:\003——探索\osrm-backend\node_modules\.stagin[           .......] | extract:tar: sill extract tar@2.2.1 extracted to D:\003——探索\osrm-backend\node_modules\.stagin[           .......] | extract:tar: sill extract tar@2.2.1 extracted to D:\003——探索\osrm-backend\node_modules\.stagin[           .......] | extract:tar: sill extract tar@2.2.1 extracted to D:\003——探索\osrm-backend\node_modules\.stagin[           .......] | extract:tar: sill extract tar@2.2.1 extracted to D:\003——探索\osrm-backend\node_modules\.stagin[           .......] | extract:tar: sill extract tar@2.2.1 extracted to D:\003——探索\osrm-backend\node_modules\.stagin[           .......] | extract:tar: sill extract tar@2.2.1 extracted to D:\003——探索\osrm-backend\node_modules\.stagin[           .......] | extract:tar: sill extract tar@2.2.1 extracted to D:\003——探索\osrm-backend\node_modules\.stagin[           .......] | extract:tar: sill extract tar@2.2.1 extracted to D:\003——探索\osrm-backend\node_modules\.stagin[            ......] - extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] - extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] - extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] - extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] - extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] - extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] - extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] - extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] - extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] / extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] / extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] / extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] / extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] / extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] / extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] / extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] / extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] / extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] / extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] / extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] / extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] / extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] / extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] / extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] / extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] / extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] / extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] / extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] / extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] / extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] / extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] / extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] / extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] - extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] \ extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] \ extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] \ extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] \ extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] \ extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] \ extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] \ extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] \ extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] \ extract:tar-pack: sill extract tar-pack@3.4.1 extracted to D:\003——探索\osrm-backend\node_modul[            ......] | refresh-package-json:uid-number: sill refresh-package-json D:\003——探索\osrm-backend\node_modulnpm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 11507 packages in 29.278s
found 5 vulnerabilities (3 low, 2 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details

D:\003——探索\osrm-backend>npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\nodejs\node_cache\_logs\2019-03-25T13_19_42_005Z-debug.log
```

**Comment by danpat** [comment]
@pig2018 We do not have a script configured for `npm start` - OSRM only really provides a library interface via NodeJS, it's not really "startable".
